openapi: 3.0.0
info:
  title: 矫正平台
  description: 该文档描述了矫正平台相关的所有 API 接口。
  version: 1.0.0

paths:
  /manage/connect:
    post:
      tags:
        - 设备管理
      summary: 订阅设备
      description: 为指定设备创建一个使用记录，写入起始时间和设备Id，并设置status。
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/useRecord"

      responses:
        "200":
          description: 使用记录添加成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/returnMsg"

  /manage/disconnect:
    put:
      tags:
        - 设备管理
      summary: 断开设备
      description: 为指定设备完善使用记录，写入结束时间，并设置status。
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/useRecord"

      responses:
        "200":
          description: 使用记录添加成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/returnMsg"

  /manage/sensor:
    put:
      tags:
        - 设备管理
      summary: 上传使用结束的传感器数据
      description: 通过包含时间戳的传感器数据列表更新指定记录的传感器数据。
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: 记录 ID。
                deviceMessageArray:
                  $ref: "#/components/schemas/deviceMessageArray"

      responses:
        "200":
          description: 记录更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/returnMsg"
    get:
      tags:
        - 设备管理
      summary: 获取设备上传的数据
      description: 根据记录 ID 获取用户相关矫正数据。
      parameters:
        - name: recordId
          in: query
          required: true
          schema:
            type: integer
          description: 记录 ID
        - name: Authorization
          in: header
          description: 令牌
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功检索设备数据
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
                  total:
                    type: integer
                  rows:
                    $ref: "#/components/schemas/deviceMessageArray"

  /manage/use:
    get:
      tags:
        - 数据管理
      summary: 获取使用记录
      description: 检索用户设备的使用记录列表。
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功检索使用记录
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  code:
                    type: integer
                  message:
                    type: string
                  rows:
                    $ref: "#/components/schemas/useRecord"

  /user/case:
    post:
      tags:
        - 数据管理
      summary: 上传病例文件
      description: 提交医生创建的病例文件。
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                case_data:
                  type: object
                  additionalProperties: true
                  description: 病例数据详情。
      responses:
        "200":
          description: 病例上传成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "病例上传成功"
                  status:
                    type: string
                    example: "success"
    get:
      tags:
        - 数据管理
      summary: 获取用户病例
      description: 获取用户的病例列表。
      parameters:
        - name: Authorization
          in: header
          description: 令牌
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功检索用户病例
          content:
            application/json:
              schema:
                type: object
                properties:
                  cases:
                    type: array
                    items:
                      type: object
                      properties:
                        case_id:
                          type: integer
                          description: 病例 ID
                        case_data:
                          type: object
                          additionalProperties: true
                          description: 病例数据

components:
  schemas:
    returnMsg:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    useRecord:
      type: object
      properties:
        recordId:
          type: integer
          description: 记录 ID。
        deviceId:
          type: integer
          description: 设备 ID。
        startTime:
          type: string
          example: yyyy-mm-dd hh:mm:ss
          description: 开始时间，格式为 'yyyy-MM-dd HH:mm:ss'。
        endTime:
          type: string
          example: yyyy-mm-dd hh:mm:ss
          description: 结束时间，格式为 'yyyy-MM-dd HH:mm:ss'。
    deviceMessageArray:
      type: array
      items:
        type: object
        properties:
          time:
            type: string
            example: yyyy-mm-dd hh:mm:ss
            description: 传感器数据的时间戳。
          sensorInfo:
            type: object
            properties:
              deviceId:
                type: integer
                description: 设备 ID。
              distance:
                type: number
                description: 传感器测量的距离。
